export const cards = [
  {
    id: 1,
    name: "Normandy",
    imageURL: "/images/all-tours/abmc_normandy.jpg",
    link: "https://tours.covecreekproductions.com/normandy/",
  },
  {
    id: 2,
    name: "Sicily-Rome",
    imageURL: "/images/all-tours/abmc_manila.jpg",
    link: "https://tours.covecreekproductions.com/sicily-rome/",
  },
  {
    id: 3,
    name: "Manila",
    imageURL: "/images/all-tours/abmc_sicily.jpg",
    link: "https://tours.covecreekproductions.com/manila/",
  },
  {
    id: 4,
    name: "Suresnes",
    imageURL: "/images/all-tours/abmc_suresnes.jpg",
    link: "https://tours.covecreekproductions.com/suresnes/",
  },
  {
    id: 5,
    name: "Honolulu Memorial",
    imageURL: "/images/all-tours/abmc_honolulu.jpg",
    link: "https://tours.covecreekproductions.com/honolulu_memorial/",
  },
  {
    id: 6,
    name: "WW1 Memorial",
    imageURL: "/images/all-tours/abmc_ww1.jpg",
    link: "https://tours.covecreekproductions.com/ww1_memorial/",
  },
  {
    id: 7,
    name: "East Coast Memorial",
    imageURL: "/images/all-tours/abmc_east_coast.jpg",
    link: "https://tours.covecreekproductions.com/east_coast_memorial/",
  },
  {
    id: 8,
    name: "West Coast Memorial",
    imageURL: "/images/all-tours/abmc_west_coast.jpg",
    link: "https://tours.covecreekproductions.com/west_coast_memorial/",
  },
  {
    id: 9,
    name: "Cambridge",
    imageURL: "/images/all-tours/abmc_cambridge.jpg",
    link: "https://tours.covecreekproductions.com/cambridge/",
  },
  {
    id: 10,
    name: "Netherlands",
    imageURL: "/images/all-tours/abmc_netherlands.jpg",
    link: "https://tours.covecreekproductions.com/netherlands/",
  },
  {
    id: 11,
    name: "Henri-Chapelle",
    imageURL: "/images/all-tours/abmc_henri.jpg",
    link: "https://tours.covecreekproductions.com/henri-chapelle/",
  },
  {
    id: 12,
    name: "Luxembourg",
    imageURL: "/images/all-tours/abmc_luxembourg.jpg",
    link: "https://tours.covecreekproductions.com/luxembourg/",
  },
  {
    id: 13,
    name: "Aisne-Marne",
    imageURL: "/images/all-tours/abmc_aisne.jpg",
    link: "https://tours.covecreekproductions.com/aisne-marne/",
  },
  {
    id: 14,
    name: "Brittany",
    imageURL: "/images/all-tours/abmc_brittany.jpg",
    link: "https://tours.covecreekproductions.com/brittany/",
  },
  {
    id: 15,
    name: "Clark",
    imageURL: "/images/all-tours/abmc_clark.jpg",
    link: "https://tours.covecreekproductions.com/clark/",
  },
  {
    id: 16,
    name: "Epinal",
    imageURL: "/images/all-tours/abmc_epinal.jpg",
    link: "https://tours.covecreekproductions.com/epinal/",
  },
  {
    id: 17,
    name: "Lafayette Escadrille",
    imageURL: "/images/all-tours/abmc_lafayette.jpg",
    link: "https://tours.covecreekproductions.com/lafayette-escadrille/",
  },
  {
    id: 18,
    name: "Oise-Aisne",
    imageURL: "/images/all-tours/abmc_oise.jpg",
    link: "https://tours.covecreekproductions.com/oise-aisne/",
  },
  {
    id: 19,
    name: "Rhone",
    imageURL: "/images/all-tours/abmc_rhone.jpg",
    link: "https://tours.covecreekproductions.com/rhone/",
  },
  {
    id: 20,
    name: "Somme",
    imageURL: "/images/all-tours/abmc_somme.jpg",
    link: "https://tours.covecreekproductions.com/somme/",
  },
  {
    id: 21,
    name: "Tunisia",
    imageURL: "/images/all-tours/abmc_tunisia.jpg",
    link: "https://tours.covecreekproductions.com/tunisia/",
  },
];
